path: plate_ocr

train: images/train
val: images/val

nc: 37
names: ['-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', ES', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']